name: hello-world-action
description: Test Action

inputs:
  name:
    description: Name
    required: true

runs:
  using: composite
  steps:
    - name: say hello
      shell: bash
      run: |
        echo "Hello action 1 ${{ inputs.name }}"
