name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    environment:
      name: dev-dev
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install awscli

#      - name: configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          role-to-assume: arn:aws:iam::775129339279:role/GithubIntegrationRole
#          role-session-name: GitHub_to_AWS_via_FederatedOIDC
#          aws-region: "us-east-2"

      # Hello from AWS: WhoAmI
#      - name: Sts GetCallerIdentity
#        run: |
#          aws sts get-caller-identity

      - name: Get Source Branch Name
        run: |
          # Extract commit SHA from the push event
          COMMIT_SHA=$(git rev-parse HEAD)

          # Fetch pull request details using GitHub API
          PR_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/pulls")

          # Extract source branch from the pull request details
          SOURCE_BRANCH=$(echo "$PR_JSON" | jq -r '.[0].head.ref')

          echo "Source Branch Name: $SOURCE_BRANCH"

      - name: Test PR branch name
        continue-on-error: true
        run: |
          echo "Github object ${{ toJson(github) }}"
          echo "1 github details ${{ toJson(github.event) }}"
          echo "2 github details ${{ github.env }}"
          echo "3 github details ${{ github.ref_name }}"
          echo "4 github details ${{ github.action }}"
          echo "5 Trigger Actor ${{ github.triggering_actor }}"
          echo "6 Ref ${{ github.github.ref }}"

