name: Deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (SHA or SemVer)'
        required: true
        type: string
        default: 'latest'
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - preview
          - prod
      stacks:
        description: 'Stacks (comma separated string)'
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      stack_groups: ${{ steps.get_stack_groups.outputs.stack_groups }}
    steps:
      - name: Install additional tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get Workflow Dispatch Inputs
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Workflow Dispatch:"
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          echo "Stacks: ${{ inputs.stacks }}"

          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "STACKS=${{ inputs.stacks }}" >> $GITHUB_ENV

      - name: Get Repository Dispatch Inputs
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Repository Dispatch:"
          echo "payload: ${{ github.event.client_payload }}"

      - name: Set Outputs
        id: set_outputs
        run: |
          echo 'print'