name: Deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (SHA or SemVer)'
        required: true
        type: string
        default: 'latest'
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - preview
          - prod
      stacks:
        description: 'Stacks (comma separated string)'
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set_outputs.outputs.ENVIRONMENT }}
      VERSION: ${{ steps.set_outputs.outputs.VERSION }}
      STACKS: ${{ steps.set_outputs.outputs.STACKS }}
    steps:
      - name: Install additional tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get Workflow Dispatch Inputs
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Workflow Dispatch:"
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          echo "Stacks: ${{ inputs.stacks }}"

          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "STACKS=${{ inputs.stacks }}" >> $GITHUB_ENV

      - name: Get Repository Dispatch Inputs
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Repository Dispatch:"
          client_payload="${{ toJson(github.event.client_payload) }}"

          environment=$(echo $client_payload | jq -r '.environment')
          version=$(echo $client_payload | jq -r '.version')
          stacks=$(echo $client_payload | jq -r '.stacks')

          echo "ENVIRONMENT=$environment" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "STACKS=$stacks" >> $GITHUB_ENV

      - name: Set Outputs
        id: set_outputs
        run: |
          echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_OUTPUT
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo "STACKS=${{ env.STACKS }}" >> $GITHUB_OUTPUT