name: Strategy Catalog Infrastructure - PR verification

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo "Ref ${{ github.head_ref }}"
          echo "sha ${{ github.sha }}"
          echo "Token ${{ github.token }}"

      - name: Create Tag
        uses: actions/github-script@v3
        env:
          TAG: 1.0.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG }}",
              sha: context.sha
            })
