name: Strategy Catalog Infrastructure - PR verification

on:
  pull_request:
    paths:
      - '**'

jobs:
  code_style:
    #    needs: build
    name: Code Style Check
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show structure
        run: |
          ls -la
          exit 1

  test:
    if: always()
    needs: code_style
    name: Test
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show structure
        shell: bash
        run: |
          ls -la
          if [[ ${{ needs.code_style.result }} == "failure" ]]; then
            exit 1
          fi
          echo "needs result ${{needs.code_style.result}}"
