name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
      - name: Install additional tools
        run: |
          apt update && apt install -y curl

      - name: Trigger Deploy
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/azverugosandbox/workflows/dispatches \
            -d '{"event_type":"deploy","client_payload":{"version": "latest","environment":"dev", "stacks": "all"}}'


